# Generated by Django 5.2.6 on 2025-11-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="establishments",
            options={
                "verbose_name": "Estabelecimento",
                "verbose_name_plural": "Estabelecimentos",
            },
        ),
        migrations.AlterModelOptions(
            name="lots",
            options={"verbose_name": "Lote", "verbose_name_plural": "Lotes"},
        ),
        migrations.AlterModelOptions(
            name="slots",
            options={"verbose_name": "Vaga", "verbose_name_plural": "Vagas"},
        ),
        migrations.AlterModelOptions(
            name="slotstatus",
            options={
                "verbose_name": "Status da Vaga",
                "verbose_name_plural": "Status das Vagas",
            },
        ),
        migrations.AlterModelOptions(
            name="slotstatushistory",
            options={
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Históricos de Status",
            },
        ),
        migrations.AlterModelOptions(
            name="slottypes",
            options={
                "verbose_name": "Tipo de Vaga",
                "verbose_name_plural": "Tipos de Vagas",
            },
        ),
        migrations.AlterModelOptions(
            name="storetypes",
            options={
                "verbose_name": "Tipo de Loja",
                "verbose_name_plural": "Tipos de Lojas",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicletypes",
            options={
                "verbose_name": "Tipo de Veículo",
                "verbose_name_plural": "Tipos de Veículos",
            },
        ),
    ]
