# Generated by Django 5.2.6 on 2025-11-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_establishments_options_alter_lots_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishments",
            name="address",
        ),
        migrations.RemoveField(
            model_name="establishments",
            name="city",
        ),
        migrations.RemoveField(
            model_name="establishments",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="establishments",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="establishments",
            name="state",
        ),
    ]
