# Generated by Django 5.2.6 on 2025-11-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_establishments_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lots',
            name='uq_lots_client_code',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='client',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='client',
        ),
        migrations.AddConstraint(
            model_name='lots',
            constraint=models.UniqueConstraint(fields=('establishment', 'lot_code'), name='uq_lots_establishment_code'),
        ),
    ]
