# Generated by Django 5.2.6 on 2025-11-18 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_redundant_client_from_lots_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('establishment', models.ForeignKey(db_column='establishment_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.establishments')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito do Usuário',
                'verbose_name_plural': 'Favoritos dos Usuários',
                'db_table': 'user_favorites',
                'indexes': [models.Index(fields=['user'], name='ix_uf_user'), models.Index(fields=['establishment'], name='ix_uf_establishment')],
                'constraints': [models.UniqueConstraint(fields=('user', 'establishment'), name='uq_user_favorites_user_establishment')],
            },
        ),
    ]
