import { Inter } from 'next/font/google' // 1. Importe a fonte
import type { Metadata } from "next";
import "./styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.ico',
  }
};


// 2. Configure e inicialize a fonte
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      {/* 3. Aplique a className na tag body */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
