# Generated by Django 5.2.6 on 2025-11-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slotstatusevents",
            options={
                "verbose_name": "Evento de Status",
                "verbose_name_plural": "Eventos de Status",
            },
        ),
    ]
