# Generated by Django 5.2.6 on 2025-11-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikeys",
            options={
                "verbose_name": "Chave de API",
                "verbose_name_plural": "Chaves de API",
            },
        ),
        migrations.AlterModelOptions(
            name="cameraheartbeats",
            options={
                "verbose_name": "Heartbeat da Câmera",
                "verbose_name_plural": "Heartbeats das Câmeras",
            },
        ),
        migrations.AlterModelOptions(
            name="cameras",
            options={"verbose_name": "Câmera", "verbose_name_plural": "Câmeras"},
        ),
    ]
