# Generated by Django 5.2.6 on 2025-11-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_remove_clientmembers_uq_client_members_client_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmembers",
            options={
                "verbose_name": "Membro do Cliente",
                "verbose_name_plural": "Membros dos Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="clients",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
    ]
